language: bash

services:
- docker

script: "./ci/docker_build.sh"

deploy:
- provider: script
  skip_cleanup: true
  script: "./ci/publish_latest.sh"
  on:
    tags: false
    branch: master
- provider: script
  skip_cleanup: true
  script: "./ci/publish_tag.sh"
  on:
    tags: true

env:
  global:
  - secure: "lv0saOGeJIztY+DlCWJvCttQ3TsE1a0nIy0PQD++QaYc1NIcY7r2a1YDHWdsNK5bHqnyMVRqe+jIfNc7BMcEm2JY1YJluwGS2CIBenQ3r0CRR1mGNR3zgFOQaIEst4uB6judwS2Bfg5FX5ZOdYmHA2xAG8ks6aB5QWlCeX9M0Kktvod78iwnrxHXDgFVhmR8gAlqmYJ5MPlULWq0PgnbDibrYVzfzxelO+m6zi5JRot+3TZh/IO8nNwW9wAEFznIFh9ObOBsdPZOF/S2i3PRzwzzHMuhXqbWnX0fLcGpZfabeRyZHS6IkOCKERDaZ+OiaWo9BTP5y74T/iZlftg80T3NNcYkvjsjcqrud0DpLbbjj6e0bn6iGrgqfEBP/zDCUD5tIFTvaZ1EQHdikYKx9gx+oA7OlaS6ncvIyAr4vFbHTNC8maIzCwkF9ZeIr8x0ibtGhZmO3c8EJf2/g3f/ne+1vOk9WBlEHirKSMarPpqre7nRGsiQKi5L7Ec6La6MUSKgcocXD8V7vETOcp8rzUxQXDstVJetjFPP6rscsALwFleDxmFEWV8TmkOosGj760gGIEIP8BlEr2/+A4v32fDCeHaZUKGCTmtuZ7+qi+C232pW5WhWmFRwv65NVAHMit8aA7ZTAKY44QY3bvQ7Kdh8GplHLqv61KzDGKQyWiM="
  - secure: "q7VX3vzKuod5duUjlsuSIhq5iUieNsH3txaBDq+6BVkAFwa9hXGDNlGDyfHfpr6WwJi+MNx78DtGiV2lHDBw/jcWyG5mJOqu5AZsR2X1isHZHuYyE8yfgHeDWNbml3pFU1oixh6dM8Qc+qvXk+TjsqJoqre2y7CGiVHUeTv/HcUPJOyoAVQyOM4MDaySzXwqNl0Pcrk4GjH+J+fbqFkwZWI120o45EBqSPqUQ7w0aRTh6Pl2U8zPi4CUGvlYhp7kCAVd3TtmKpt8E1FiMBEwMhVWJG5G1MNlDLAFCZ0LmzlqLJyjbPE7KUG5puezQ+LWWip+nqvL1M3v4QD22Nv8ZwCmbZ0T4U1bjC6eFcK0kVVH84Grk0QDjhjdbnUz2q+oVZMpFqg/kKELUNjvjKAtIhmh0+muezQa6+aZ/iDWuUVXd/WHNRIqsGjZWqOFU0prfaJrobzyPf0WyG8NzdYNqp5X4NdUIiG+1ytGa7GMzf94ycxVS/YYiGuI1BsZkT8JlA1JfpIe+kJrkaT0DF8gl5+/5UM7u3Et0gfzJOug5hv3ZNQoWgQsTcOd+JyIfFpCbCWz6p+DlTb5E8YZgARpiFBe78mhV8dnmqPccS9rLrag6ZA7++/whEhjYSGb6sNp+ZWs5+XK5rn0gwQR9daTpBT0C6WWwOj6UFTdvvvL7pg="
  - secure: "VE3cBR7H8KF5dm53NT58hkB9cbMv5GuIYq+T+fNURgGR9H5wgB1O61KB5RySUroUIoONaTiQ2zWMDKcjrS2c58brjRcsWH25jplxPs94LaFsUA7i7y1X3Yj8wmAlp/f/xKONQd5F9zwlsyyOxTaDM5S+DS6VsbsRDwQrsGAh9xEjhH17wS5VU+yG3r16cqucuk6fVTBf/G0dwer8IWqp7HyX0GJC8reYaPC/HrNwENhRl/FCKcgTSiaJmMsW77Gac2TrnG1CGIgGVXYknWZQqVKedotMRJvzVbBhKpsLDZ6TifrSsjqMNvcIE+beKBvWorO/gTHvMbf5sg/L2tb5lVD+AAvwoxb3USZ3Q72YFH46LS5ZZlK23hVs06f18dVBPzIusqCLSmBZGUSy2udUSOdz6Rkjyqk6jGXvCpL/Wuat+0t9o6rf6nAxoPtix3kJYH1ggJJqoJPT4YWLWvT6NxLlx7uSXuZiZfbb3u20WSI3WvE/aDp2x3NGP1tvZkqGK24VJcJ4EYJR0br8QHwl0koZcuq+vCBMuYT/jMUGouqlrtYDS+C0t39LZij3phOwI7SvHVtfCf/dlZGM/q3sPXolVZjs+ITB/r14GiseTiB+be4szC5rLCWaMHDg4QcAogCNeyiocim85+lX66fEJsTRKWQEVFqYqkldF1uuo40="
  - secure: "VmICPIwNt6ahAHIhSaxtSx0hpkMh7ZJ9STxPhLVdiB6Y1XDxpnTrCOc676aQcQELLjAj8ObRpNFY2QOfd45Aq/c3TAjs5yUR+vPscXJJiUd6wTMeAjIhesjZezUHiSPlZsYYsoYi9dIgzfXFhp0DQqdgJks4MUnVgPr+Z78ALH1VMA1PJhZNOtkT4fRlrHG/AfS1gCg+w2gm2xMmQFYlNO3xOLuKmg7HGV/EfemXIzjws+LBxs9fwqy/UYgIunLAEQPT4TH8q//i1Mcc22h46Im2/TxxjuS787aWNk8b7dZvxMEJIIcCGXqN4JUl33aOvId/kb4pzPaN4DfxNsrNTDWRU3OhUl3hsuR9pC+Dm2YgmC+B57xLvnCw/ez+cIHcR6JOGV6/E0GcmnkBUWUCmkByZlbSFnarnHTTTzQVO4CFjCFYXSw0tgnI0L9TWQb5MHiG1ZaVB41dWsqTt9wYw2Yh6s8wISEnMF7ke4nwPfWRaCNeA9tZdhXsZBABWTOy0dRUUQn74baBUAiHVZ3Z6XmeYxOrbdmThsSkCY7Tz647zxTpSoximDVPpuM5EhrivktLyglGSZH8KngloB38xL/vAs3FSvEssB7Rz+q91Ckp1dUg++Vzi9qw1hNjDrNetKV2VLwN1Va9jDGhqATUQngdDI4AE9x4uUgRJrqh8fY="
